Vagrant.configure(2) do |config|
  config.vm.box = "mesos"

  config.vm.network "forwarded_port", guest: 5050, host: 5050
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    rm /etc/init/zookeeper.override
    service zookeeper start

    rm /etc/init/mesos-master.override
    service mesos-master start

    rm /etc/init/mesos-slave.override
    service mesos-slave start

    rm /etc/init/marathon.override
    service marathon start
  SHELL
end
